// Microscope Session Modal Component
// This file handles the microscope session modal functionality

import { showAlert } from "./alertSystem.js";
import { getCurrentDateForInput } from "../utils/dateUtils.js";

// Microscope Session Modal Functions
export function setupMicroscopeSessionModal() {
  const modal = document.getElementById("microscopeSessionModal");
  const closeBtn = modal?.querySelector(".close-modal");

  if (closeBtn) {
    closeBtn.addEventListener("click", closeMicroscopeSessionModal);
  }

  if (modal) {
    modal.addEventListener("click", (e) => {
      if (e.target === modal) closeMicroscopeSessionModal();
    });
  }
}

export function openMicroscopeSessionModal() {
  const modal = document.getElementById("microscopeSessionModal");
  const content = document.getElementById("microscopeSessionModalContent");

  if (modal && content) {
    // Add wide class for this modal
    modal.querySelector(".modal-content").classList.add("wide");

    // Load the form content
    content.innerHTML = generateMicroscopeSessionForm();
    setupMicroscopeSessionForm();

    modal.style.display = "block";
    document.body.classList.add("modal-open");
  }
}

function closeMicroscopeSessionModal() {
  const modal = document.getElementById("microscopeSessionModal");
  if (modal) {
    modal.style.display = "none";
    document.body.classList.remove("modal-open");
    // Remove wide class
    modal.querySelector(".modal-content").classList.remove("wide");
  }
}

function generateMicroscopeSessionForm() {
  const todayDate = getCurrentDateForInput();
  return `
    <h2>New Microscope Session</h2>
    <form id="microscopeSessionForm">
      <div class="session-info-grid">
        <div class="form-group">
          <label for="sessionDate">Date *</label>
          <input type="date" name="date" id="sessionDate" value="${todayDate}" required />
        </div>
        <div class="form-group">
          <label for="sessionMicroscope">Microscope *</label>
          <input type="text" name="microscope" id="sessionMicroscope" required placeholder="e.g. Krios1" />
        </div>
        <div class="form-group checkbox-group">
          <input type="checkbox" id="sessionOvernight" name="overnight" />
          <label for="sessionOvernight">Overnight Session</label>
        </div>
        <div class="form-group checkbox-group">
          <input type="checkbox" id="sessionClipped" name="clipped_at_microscope" />
          <label for="sessionClipped">Clipped at Microscope</label>
        </div>
        <div class="form-group" style="grid-column: 1 / -1;">
          <label for="sessionIssues">Issues/Notes</label>
          <textarea name="issues" id="sessionIssues" rows="2" placeholder="Any issues or notes about the session"></textarea>
        </div>
      </div>

      <h3>Grid Slots (12 slots)</h3>
      <div class="microscope-table-container">
        <table class="grid-detail-table">
          <thead>
            <tr>
              <th>Slot</th>
              <th>Grid Identifier</th>
              <th>Atlas</th>
              <th>Screened</th>
              <th>Collected</th>
              <th>Grid Quality</th>
              <th>Particle Number</th>
              <th>Ice Quality</th>
              <th>Rescued</th>
              <th>Comments</th>
            </tr>
          </thead>
          <tbody id="microscopeSlotsTableBody">
            <!-- Rows will be generated by JS -->
          </tbody>
        </table>
      </div>

      <div class="button-group" style="margin-top: 20px; text-align: center;">
        <button type="submit" class="btn btn-primary">Save Session</button>
        <button type="button" id="cancelMicroscopeSession" class="btn btn-secondary">Cancel</button>
      </div>
    </form>
  `;
}

function setupMicroscopeSessionForm() {
  const form = document.getElementById("microscopeSessionForm");
  const cancelBtn = document.getElementById("cancelMicroscopeSession");

  // Set default date to today (with small delay to ensure DOM is ready)
  setTimeout(() => {
    const dateInput = document.getElementById("sessionDate");
    if (dateInput) {
      dateInput.value = getCurrentDateForInput();
    }
  }, 10);

  // Generate 12 rows for slots
  generateMicroscopeSlotRows();

  // Setup star ratings after rows are generated
  setupStarRatings();

  // Handle form submission
  if (form) {
    form.addEventListener("submit", handleMicroscopeSessionSubmit);
  }

  // Handle cancel button
  if (cancelBtn) {
    cancelBtn.addEventListener("click", closeMicroscopeSessionModal);
  }
}

function generateMicroscopeSlotRows() {
  const tbody = document.getElementById("microscopeSlotsTableBody");
  if (!tbody) return;

  tbody.innerHTML = "";
  for (let i = 12; i >= 1; i--) {
    const tr = document.createElement("tr");
    tr.dataset.slot = i;
    tr.innerHTML = `
      <td><strong>${i}</strong></td>
      <td><input name="grid_identifier[]" type="text" placeholder="e.g. JS001g1" style="width: 100%;" /></td>
      <td><input name="atlas[]" type="checkbox" /></td>
      <td><select name="screened[]" style="width: 100%;">
        <option value="">Select...</option>
        <option value="no">No</option>
        <option value="manually">Manually</option>
        <option value="automatically">Automatically</option>
      </select></td>
      <td><input name="collected[]" type="checkbox" /></td>
      <td><div class="star-rating" data-field="grid_quality" data-slot="${i}">
        <span class="star" data-value="1">★</span>
        <span class="star" data-value="2">★</span>
        <span class="star" data-value="3">★</span>
        <span class="star" data-value="4">★</span>
        <span class="star" data-value="5">★</span>
        <input type="hidden" name="grid_quality[]" value="0" />
      </div></td>
      <td><div class="star-rating" data-field="particle_number" data-slot="${i}">
        <span class="star" data-value="1">★</span>
        <span class="star" data-value="2">★</span>
        <span class="star" data-value="3">★</span>
        <span class="star" data-value="4">★</span>
        <span class="star" data-value="5">★</span>
        <input type="hidden" name="particle_number[]" value="0" />
      </div></td>
      <td><div class="star-rating" data-field="ice_quality" data-slot="${i}">
        <span class="star" data-value="1">★</span>
        <span class="star" data-value="2">★</span>
        <span class="star" data-value="3">★</span>
        <span class="star" data-value="4">★</span>
        <span class="star" data-value="5">★</span>
        <input type="hidden" name="ice_quality[]" value="0" />
      </div></td>
      <td><input name="rescued[]" type="checkbox" /></td>
      <td><textarea name="comments[]" placeholder="Notes" style="width: 100%; height: 40px; resize: vertical; box-sizing: border-box;" rows="2"></textarea></td>
    `;
    tbody.appendChild(tr);
  }
}

async function handleMicroscopeSessionSubmit(event) {
  event.preventDefault();

  const form = event.target;
  const formData = new FormData(form);

  // Collect slot details
  const details = [];
  const tbody = document.getElementById("microscopeSlotsTableBody");
  tbody.querySelectorAll("tr").forEach((tr) => {
    const grid_identifier = tr
      .querySelector('[name="grid_identifier[]"]')
      .value.trim();
    if (grid_identifier) {
      details.push({
        microscope_slot: parseInt(tr.dataset.slot),
        grid_identifier: grid_identifier,
        atlas: tr.querySelector('[name="atlas[]"]').checked ? 1 : 0,
        screened: tr.querySelector('[name="screened[]"]').value.trim() || null,
        collected: tr.querySelector('[name="collected[]"]').checked ? 1 : 0,
        grid_quality: tr.querySelector('[name="grid_quality[]"]').value || null,
        particle_number:
          tr.querySelector('[name="particle_number[]"]').value || null,
        ice_quality: tr.querySelector('[name="ice_quality[]"]').value || null,
        rescued: tr.querySelector('[name="rescued[]"]').checked ? 1 : 0,
        comments: tr.querySelector('[name="comments[]"]').value.trim() || null,
      });
    }
  });

  const payload = {
    date: formData.get("date"),
    microscope: formData.get("microscope"),
    overnight: formData.get("overnight") ? 1 : 0,
    clipped_at_microscope: formData.get("clipped_at_microscope") ? 1 : 0,
    issues: formData.get("issues") || null,
    details: details,
  };

  try {
    const response = await fetch("/api/microscope-sessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || `Server returned ${response.status}`);
    }

    const result = await response.json();
    showAlert(
      `Microscope session saved successfully! Session ID: ${result.id}`,
      "success"
    );
    closeMicroscopeSessionModal();
  } catch (error) {
    console.error("Error saving microscope session:", error);
    showAlert(`Failed to save session: ${error.message}`, "error");
  }
}

// Star Rating Functions
function setupStarRatings() {
  const starRatings = document.querySelectorAll(".star-rating");

  starRatings.forEach((rating) => {
    const stars = rating.querySelectorAll(".star");
    const hiddenInput = rating.querySelector('input[type="hidden"]');

    stars.forEach((star) => {
      // Add hover effect
      star.addEventListener("mouseenter", () => {
        const value = parseInt(star.dataset.value);
        highlightStars(rating, value);
      });

      // Click to set rating
      star.addEventListener("click", () => {
        const value = parseInt(star.dataset.value);
        setStarRating(rating, value);
        hiddenInput.value = value;
      });
    });

    // Reset on mouse leave
    rating.addEventListener("mouseleave", () => {
      const currentValue = parseInt(hiddenInput.value);
      highlightStars(rating, currentValue);
    });
  });
}

function highlightStars(ratingContainer, value) {
  const stars = ratingContainer.querySelectorAll(".star");
  stars.forEach((star, index) => {
    if (index < value) {
      star.classList.add("active");
      star.classList.remove("inactive");
    } else {
      star.classList.remove("active");
      star.classList.add("inactive");
    }
  });
}

function setStarRating(ratingContainer, value) {
  const hiddenInput = ratingContainer.querySelector('input[type="hidden"]');
  hiddenInput.value = value;
  highlightStars(ratingContainer, value);
}
