// Microscope Session Modal Component
// This file handles the microscope session modal functionality

import { showAlert } from "./alertSystem.js";
import { getCurrentDateForInput } from "../utils/dateUtils.js";
import {
  renderInteractiveStarRating,
  setupStarRatings,
} from "../utils/starRating.js";

// Global variable to track current session ID for updates
let currentSessionId = null;

// Global callback for when session is saved/updated
let onSessionSavedCallback = null;

// Microscope Session Modal Functions
export function setupMicroscopeSessionModal() {
  const modal = document.getElementById("microscopeSessionModal");
  const closeBtn = modal?.querySelector(".close-modal");

  if (closeBtn) {
    closeBtn.addEventListener("click", closeMicroscopeSessionModal);
  }

  if (modal) {
    modal.addEventListener("click", (e) => {
      if (e.target === modal) closeMicroscopeSessionModal();
    });
  }
}

export function openMicroscopeSessionModal(
  sessionId = null,
  onSavedCallback = null
) {
  const modal = document.getElementById("microscopeSessionModal");
  const content = document.getElementById("microscopeSessionModalContent");

  if (modal && content) {
    // Set session tracking based on parameter
    currentSessionId = sessionId;
    onSessionSavedCallback = onSavedCallback;

    // Add wide class for this modal
    modal.querySelector(".modal-content").classList.add("wide");

    // Load the form content
    content.innerHTML = generateMicroscopeSessionForm();
    setupMicroscopeSessionForm();

    modal.style.display = "block";
    document.body.classList.add("modal-open");
  }
}

// Function to set the current session ID (for editing)
export function setCurrentSessionId(sessionId) {
  currentSessionId = sessionId;
}

// Function to get the current session ID
export function getCurrentSessionId() {
  return currentSessionId;
}

function closeMicroscopeSessionModal() {
  const modal = document.getElementById("microscopeSessionModal");
  if (modal) {
    modal.style.display = "none";
    document.body.classList.remove("modal-open");
    // Remove wide class
    modal.querySelector(".modal-content").classList.remove("wide");
    // Reset session tracking when closing
    currentSessionId = null;
    onSessionSavedCallback = null;
  }
}

function generateMicroscopeSessionForm() {
  const todayDate = getCurrentDateForInput();
  return `
    <h2>New Microscope Session</h2>
    <form id="microscopeSessionForm">
      <div class="session-info-grid">
        <div class="form-group">
          <label for="sessionDate">Date *</label>
          <input type="date" name="date" id="sessionDate" value="${todayDate}" required />
        </div>
        <div class="form-group">
          <label for="sessionMicroscope">Microscope *</label>
          <input type="text" name="microscope" id="sessionMicroscope" required placeholder="e.g. Krios1" />
        </div>
        <div class="form-group checkbox-group">
          <input type="checkbox" id="sessionOvernight" name="overnight" />
          <label for="sessionOvernight">Overnight Session</label>
        </div>
        <div class="form-group checkbox-group">
          <input type="checkbox" id="sessionClipped" name="clipped_at_microscope" />
          <label for="sessionClipped">Clipped at Microscope</label>
        </div>
        <div class="form-group" style="grid-column: 1 / -1;">
          <label for="sessionIssues">Issues/Notes</label>
          <textarea name="issues" id="sessionIssues" rows="2" placeholder="Any issues or notes about the session"></textarea>
        </div>
      </div>

      <h3>Grid Slots (12 slots)</h3>
      <div class="microscope-table-container">
        <table class="grid-detail-table">
          <thead>
            <tr>
              <th>Slot</th>
              <th>Grid Identifier</th>
              <th>Atlas</th>
              <th>Screened</th>
              <th>Collected</th>
              <th>Grid Quality</th>
              <th>Particle Number</th>
              <th>Ice Quality</th>
              <th>Rescued</th>
              <th>Comments</th>
            </tr>
          </thead>
          <tbody id="microscopeSlotsTableBody">
            <!-- Rows will be generated by JS -->
          </tbody>
        </table>
      </div>

      <div class="button-group" style="margin-top: 20px; text-align: center;">
        <button type="submit" class="btn btn-primary">Save Session</button>
        <button type="button" id="cancelMicroscopeSession" class="btn btn-secondary">Cancel</button>
      </div>
    </form>
  `;
}

function setupMicroscopeSessionForm() {
  const form = document.getElementById("microscopeSessionForm");
  const cancelBtn = document.getElementById("cancelMicroscopeSession");

  // Set default date to today (with small delay to ensure DOM is ready)
  setTimeout(() => {
    const dateInput = document.getElementById("sessionDate");
    if (dateInput) {
      dateInput.value = getCurrentDateForInput();
    }
  }, 10);

  // Generate 12 rows for slots
  generateMicroscopeSlotRows();

  // Setup star ratings after rows are generated
  setupStarRatings();

  // Setup foldout functionality for collected checkboxes
  setupCollectedFoldouts();

  // Handle form submission
  if (form) {
    form.addEventListener("submit", handleMicroscopeSessionSubmit);
  }

  // Handle cancel button
  if (cancelBtn) {
    cancelBtn.addEventListener("click", closeMicroscopeSessionModal);
  }
}

function generateMicroscopeSlotRows() {
  const tbody = document.getElementById("microscopeSlotsTableBody");
  if (!tbody) return;

  tbody.innerHTML = "";
  for (let i = 12; i >= 1; i--) {
    const tr = document.createElement("tr");
    tr.dataset.slot = i;
    tr.innerHTML = `
      <td><strong>${i}</strong></td>
      <td><input name="grid_identifier[]" type="text" placeholder="e.g. JS001g1" style="width: 100%;" /></td>
      <td><input name="atlas[]" type="checkbox" /></td>
      <td><select name="screened[]" style="width: 100%;">
        <option value="">Select...</option>
        <option value="no">No</option>
        <option value="manually">Manually</option>
        <option value="automatically">Automatically</option>
      </select></td>
      <td><input name="collected[]" type="checkbox" /></td>
      <td>${renderInteractiveStarRating("grid_quality", i, 0)}</td>
      <td>${renderInteractiveStarRating("particle_number", i, 0)}</td>
      <td>${renderInteractiveStarRating("ice_quality", i, 0)}</td>
      <td><input name="rescued[]" type="checkbox" /></td>
      <td><textarea name="comments[]" placeholder="Notes" style="width: 100%; height: 40px; resize: vertical; box-sizing: border-box;" rows="2"></textarea></td>
    `;
    tbody.appendChild(tr);

    // Add the foldout row for additional microscope details
    const foldoutRow = document.createElement("tr");
    foldoutRow.className = "expandable-row microscope-foldout";
    foldoutRow.dataset.slot = i;
    foldoutRow.innerHTML = `
      <td colspan="10">
        <div class="expandable-content microscope-details" id="microscope-details-${i}">
          <h4 class="detail-subtitle">Collection Details for Slot ${i}</h4>
          <div class="microscope-details-grid">
            <div class="form-group">
              <label>Multigrid</label>
              <input name="multigrid[]" type="checkbox" />
            </div>
            <div class="form-group">
              <label>Px Size (Å)</label>
              <input name="px_size[]" type="number" step="0.001" placeholder="e.g. 1.06" />
            </div>
            <div class="form-group">
              <label>Magnification</label>
              <input name="magnification[]" type="number" placeholder="e.g. 81000" />
            </div>
            <div class="form-group">
              <label>Exposure (e/Å²)</label>
              <input name="exposure_e[]" type="number" step="1" placeholder="e.g. 40" />
            </div>
            <div class="form-group">
              <label>Exposure Time (s)</label>
              <input name="exposure_time[]" type="number" step="0.1" placeholder="e.g. 2.5" />
            </div>
            <div class="form-group">
              <label>Spot Size</label>
              <input name="spot_size[]" type="number" placeholder="e.g. 4" />
            </div>
            <div class="form-group">
              <label>Illumination Area</label>
              <input name="illumination_area[]" type="number" step="0.01" placeholder="e.g. 3.5" />
            </div>
            <div class="form-group">
              <label>Exp per Hole</label>
              <input name="exp_per_hole[]" type="number" placeholder="e.g. 3" />
            </div>
            <div class="form-group">
              <label>Images</label>
              <input name="images[]" type="number" placeholder="e.g. 1500" />
            </div>
            <div class="form-group">
              <label>Nominal Defocus</label>
              <input name="nominal_defocus[]" type="text" placeholder="e.g. -1.5 to -2.5" />
            </div>
            <div class="form-group">
              <label>Objective</label>
              <input name="objective[]" type="number" placeholder="e.g. 100" />
            </div>
            <div class="form-group">
              <label>Slit Width</label>
              <input name="slit_width[]" type="number" placeholder="e.g. 20" />
            </div>
          </div>
        </div>
      </td>
    `;
    tbody.appendChild(foldoutRow);
  }
}

async function handleMicroscopeSessionSubmit(event) {
  event.preventDefault();

  const form = event.target;
  const formData = new FormData(form);

  // Collect slot details
  const details = [];
  const tbody = document.getElementById("microscopeSlotsTableBody");
  tbody.querySelectorAll("tr").forEach((tr) => {
    // Skip foldout rows - only process main slot rows
    if (tr.classList.contains("microscope-foldout")) {
      return;
    }

    const gridIdentifierElement = tr.querySelector(
      '[name="grid_identifier[]"]'
    );
    if (!gridIdentifierElement) {
      return; // Skip if this isn't a main slot row
    }

    const grid_identifier = gridIdentifierElement.value.trim();
    if (grid_identifier) {
      const collectedElement = tr.querySelector('[name="collected[]"]');
      const detail = {
        microscope_slot: parseInt(tr.dataset.slot),
        grid_identifier: grid_identifier,
        atlas: tr.querySelector('[name="atlas[]"]').checked ? 1 : 0,
        screened: tr.querySelector('[name="screened[]"]').value.trim() || null,
        collected: collectedElement ? (collectedElement.checked ? 1 : 0) : 0,
        grid_quality: tr.querySelector('[name="grid_quality[]"]').value || null,
        particle_number:
          tr.querySelector('[name="particle_number[]"]').value || null,
        ice_quality: tr.querySelector('[name="ice_quality[]"]').value || null,
        rescued: tr.querySelector('[name="rescued[]"]').checked ? 1 : 0,
        comments: tr.querySelector('[name="comments[]"]').value.trim() || null,
      };

      // Add additional microscope details if collected checkbox is checked
      if (collectedElement && collectedElement.checked) {
        const slot = tr.dataset.slot;
        const foldoutRow = document.querySelector(
          `.microscope-foldout[data-slot="${slot}"]`
        );

        if (foldoutRow) {
          const multigridElement = foldoutRow.querySelector(
            '[name="multigrid[]"]'
          );
          const pxSizeElement = foldoutRow.querySelector('[name="px_size[]"]');
          const magnificationElement = foldoutRow.querySelector(
            '[name="magnification[]"]'
          );
          const exposureEElement = foldoutRow.querySelector(
            '[name="exposure_e[]"]'
          );
          const exposureTimeElement = foldoutRow.querySelector(
            '[name="exposure_time[]"]'
          );
          const spotSizeElement = foldoutRow.querySelector(
            '[name="spot_size[]"]'
          );
          const illuminationAreaElement = foldoutRow.querySelector(
            '[name="illumination_area[]"]'
          );
          const expPerHoleElement = foldoutRow.querySelector(
            '[name="exp_per_hole[]"]'
          );
          const imagesElement = foldoutRow.querySelector('[name="images[]"]');
          const nominalDefocusElement = foldoutRow.querySelector(
            '[name="nominal_defocus[]"]'
          );
          const objectiveElement = foldoutRow.querySelector(
            '[name="objective[]"]'
          );
          const slitWidthElement = foldoutRow.querySelector(
            '[name="slit_width[]"]'
          );

          detail.multigrid = multigridElement
            ? multigridElement.checked
              ? 1
              : 0
            : 0;
          detail.px_size = pxSizeElement ? pxSizeElement.value || null : null;
          detail.magnification = magnificationElement
            ? magnificationElement.value || null
            : null;
          detail.exposure_e = exposureEElement
            ? exposureEElement.value || null
            : null;
          detail.exposure_time = exposureTimeElement
            ? exposureTimeElement.value || null
            : null;
          detail.spot_size = spotSizeElement
            ? spotSizeElement.value || null
            : null;
          detail.illumination_area = illuminationAreaElement
            ? illuminationAreaElement.value || null
            : null;
          detail.exp_per_hole = expPerHoleElement
            ? expPerHoleElement.value || null
            : null;
          detail.images = imagesElement ? imagesElement.value || null : null;
          detail.nominal_defocus = nominalDefocusElement
            ? nominalDefocusElement.value.trim() || null
            : null;
          detail.objective = objectiveElement
            ? objectiveElement.value || null
            : null;
          detail.slit_width = slitWidthElement
            ? slitWidthElement.value || null
            : null;
        }
      }

      details.push(detail);
    }
  });

  const payload = {
    date: formData.get("date"),
    microscope: formData.get("microscope"),
    overnight: formData.get("overnight") ? 1 : 0,
    clipped_at_microscope: formData.get("clipped_at_microscope") ? 1 : 0,
    issues: formData.get("issues") || null,
    details: details,
  };

  try {
    // Determine if this is a new session or an update
    const isUpdate = currentSessionId !== null;
    const method = isUpdate ? "PUT" : "POST";
    const url = isUpdate
      ? `/api/microscope-sessions/${currentSessionId}`
      : "/api/microscope-sessions";

    const response = await fetch(url, {
      method: method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || `Server returned ${response.status}`);
    }

    const result = await response.json();

    if (isUpdate) {
      showAlert(
        `Microscope session updated successfully! Session ID: ${currentSessionId}`,
        "success"
      );
      // Call the callback to refresh the admin table
      if (onSessionSavedCallback) {
        onSessionSavedCallback();
      }
    } else {
      // First save - store the session ID and change button text
      currentSessionId = result.id;
      const submitButton = document.querySelector(
        '#microscopeSessionForm button[type="submit"]'
      );
      if (submitButton) {
        submitButton.textContent = "Update Session";
      }
      showAlert(
        `Microscope session saved successfully! Session ID: ${result.id}`,
        "success"
      );
      // Call the callback to refresh the admin table
      if (onSessionSavedCallback) {
        onSessionSavedCallback();
      }
    }

    // Don't close the modal - keep it open for further edits
  } catch (error) {
    console.error("Error saving microscope session:", error);
    showAlert(`Failed to save session: ${error.message}`, "error");
  }
}

// Foldout Functions
function setupCollectedFoldouts() {
  const collectedCheckboxes = document.querySelectorAll(
    'input[name="collected[]"]'
  );

  collectedCheckboxes.forEach((checkbox) => {
    checkbox.addEventListener("change", function () {
      const row = this.closest("tr");
      const slot = row.dataset.slot;
      const foldoutRow = document.querySelector(
        `.microscope-foldout[data-slot="${slot}"]`
      );
      const content = document.getElementById(`microscope-details-${slot}`);

      if (this.checked) {
        // Show foldout
        foldoutRow.classList.add("visible");
        content.classList.add("expanded");
      } else {
        // Hide foldout and clear values
        foldoutRow.classList.remove("visible");
        content.classList.remove("expanded");
        clearFoldoutValues(slot);
      }
    });
  });
}

function clearFoldoutValues(slot) {
  const foldoutRow = document.querySelector(
    `.microscope-foldout[data-slot="${slot}"]`
  );
  if (foldoutRow) {
    const inputs = foldoutRow.querySelectorAll("input");
    inputs.forEach((input) => {
      if (input.type === "checkbox") {
        input.checked = false;
      } else {
        input.value = "";
      }
    });
  }
}
